---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: registry-auth
    namespace: argo
  type: Opaque
  stringData:
    config.json: '{"auths":{"harbor.CHANGE_ME.internal":{"username":"CHANGE_ME","password":"CHANGE_ME"}}}'
- apiVersion: v1
  kind: Secret
  metadata:
    name: bitbucket-ssh
    namespace: argo
  type: Opaque
  stringData:
    id_rsa: 'CHANGE_ME

'
    known_hosts: 'bitbucket.CHANGE_ME.internal ssh-ed25519 CHANGE_ME

'
